var googleArr=
[
{ "_id" : { "$oid" : "536568717d0ca84268af9116" }, "category" : [ "/music/artist" ], "ctgl" : [ "/broadcast/artist", "/music/artist", "/music/musical_group", "/music/group_member", "/common/topic" ], "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcRnG1-2oXpaWlNeHmxhOMjPTuTW-5rRIRGnLCFtyNJtyQZOJ0daJssiP94tEacnAipw2LR5xm7Q", "rank" : "1", "sdoid" : "2", "search_count" : ">10000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:01:14 +0000", "title" : "John Boyega", "url" : "www.businessinsider.com/who-is-john-boyega-star-wars-2014-4", "woeid" : "23424977" },
{ "_id" : { "$oid" : "536568717d0ca84268af9117" }, "category" : [ "/computer/software", "/computer/web_browser" ], "ctgl" : [ "/computer/software", "/computer/web_browser", "/user/jeffrey/default_domain/software_project", "/user/vtalwar/default_domain/logoed_topic", "/base/argumentmaps/thing_of_disputed_value", "/base/argumentmaps/topic", "/computer/operating_system", "/common/topic" ], "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcQuz7Shd-QTRH7x3DdbQHAJQu_zde_Jn-GaodYHE9OVT3UNWzpJXaqqGyJAN0zaBXncspy-BfzY", "rank" : "2", "sdoid" : "2", "search_count" : ">10000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:01:14 +0000", "title" : "Firefox", "url" : "www.hollywoodreporter.com/live-feed/video-emma-stone-takes-jimmy-699541", "woeid" : "23424977" },
{ "_id" : { "$oid" : "536568717d0ca84268af9118" }, "category" : [ "/people/person", "/common/topic" ], "ctgl" : [ "/people/person", "/common/topic" ], "image_url" : "t0.gstatic.com/images?q=tbn:ANd9GcRo41cPva0vLIzw7748_TFEx3zlqRD974w8_hfPP37IBHV4HWVjL7RFoMNwagBhRe4sSwbbaEo", "rank" : "3", "sdoid" : "2", "search_count" : ">5000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:01:14 +0000", "title" : "Emma Stone", "url" : "www.techrepublic.com/article/chrome-tablet-will-google-reboot-its-mobile-strategy/", "woeid" : "23424977" },
{ "_id" : { "$oid" : "536568717d0ca84268af9119" }, "category" : [ "/computer/software_developer", "/user/joehughes/default_domain/transit_application_creator" ], "ctgl" : [ "/computer/software_developer", "/user/joehughes/default_domain/transit_application_creator", "/business/employer", "/user/rcheramy/default_domain/manufacturer", "/venture_capital/venture_funded_company", "/internet/website_owner", "/venture_capital/venture_investor", "/user/robert/default_domain/logos", "/award/award_presenting_organization", "/base/database/topic", "/base/database/database_financial_supporter", "/base/database/database_host", "/book/book_subject", "/organization/organization_founder", "/organization/organization_member", "/award/ranked_item", "/internet/social_network_user", "/user/vtalwar/default_domain/logoed_topic", "/base/onewayshopping/topic", "/computer/operating_system_developer", "/base/informationtechnology/topic", "/business/sponsor", "/user/mr_kav/default_domain/program", "/base/argumentmaps/thing_of_disputed_value", "/base/argumentmaps/topic", "/base/adidtest/topic", "/business/business_operation", "/business/issuer", "/base/todolists/topic", "/computer/programming_language_developer", "/user/uoa_it/uoa_it/uoa_vendor", "/user/uoa_it/uoa_it/topic", "/organization/organization", "/base/internettechnology/topic", "/m/0cgxpqv", "/m/0cgyc3f", "/base/ovguide/topic", "/business/consumer_company", "/conferences/conference_sponsor", "/user/whurrraywebworld/default_domain/whurray", "/base/ecology/topic", "/projects/project_participant", "/law/patent_assignee", "/base/technologyofdoing/proposal_agent", "/computer/computer_manufacturer_brand", "/user/robert/mobile_phones/mobile_phone_brand", "/user/robert/mobile_phones/product_brand", "/law/litigant", "/dataworld/data_provider", "/base/schemastaging/organization_extra", "/user/alust/default_domain/processed_with_review_queue", "/film/film_subject", "/conferences/conference_subject", "/freebase/list", "/award/award_winner", "/architecture/architectural_structure_owner", "/m/04mny2g", "/user/micahsaul/advertising/advertiser", "/award/award_nominee", "/location/location", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcTp2PfDHxjI9wzG9x0H-DY2lgtpp8feOqJNsXlXwI2s3DJ-ND_83pm8V_ypXhZBruJvj72Di-Bt", "rank" : "4", "sdoid" : "2", "search_count" : ">5000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:01:14 +0000", "title" : "Google Chrome", "url" : "www.theguardian.com/world/2014/apr/29/john-kerry-apologises-israel-apartheid-remarks", "woeid" : "23424977" },
{ "_id" : { "$oid" : "536568717d0ca84268af911a" }, "category" : [ "/time/event", "/base/culturalevent/event" ], "ctgl" : [ "/time/event", "/base/culturalevent/event", "/film/film_subject", "/common/topic" ], "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcTMCCybCON6tWITW2f2RCXqgjDyzysh-G82tkKCelEOXboh6fg62XYrIph8jfHSYWZlmOlDFTc", "rank" : "5", "sdoid" : "2", "search_count" : ">5000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:01:14 +0000", "title" : "apartheid", "url" : "www.csmonitor.com/World/Latest-News-Wires/2014/0429/Malaysia-evaluating-claims-of-plane-wreckage-in-Bay-of-Bengal-new-investigator-hired", "woeid" : "23424977" },
{ "_id" : { "$oid" : "536568717d0ca84268af911b" }, "category" : [ "/location/location", "/base/aubreymaturin/place" ], "ctgl" : [ "/location/location", "/base/aubreymaturin/place", "/fictional_universe/fictional_setting", "/base/aubreymaturin/topic", "/base/aubreymaturin/real_place", "/government/governmental_jurisdiction", "/location/dated_location", "/location/statistical_region", "/periodicals/newspaper_circulation_area", "/location/administrative_division", "/common/topic" ], "image_url" : "t0.gstatic.com/images?q=tbn:ANd9GcS66wJWcuz_ZqN9dM-ODNoZvLq8PHhnqBCPeqDjGwZZl9URh_r6o0o2CzbLE2XsaloP-tU_TKg", "rank" : "6", "sdoid" : "2", "search_count" : ">5000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:01:14 +0000", "title" : "Bay of Bengal", "url" : "www.abc3340.com/story/25374035/storms-caused-heavy-damage-in-graysville", "woeid" : "23424977" },
{ "_id" : { "$oid" : "536568717d0ca84268af911c" }, "category" : [ "/location/location", "/geography/river" ], "ctgl" : [ "/location/location", "/geography/river", "/geography/body_of_water", "/geography/geographical_feature", "/common/topic" ], "image_url" : "t3.gstatic.com/images?q=tbn:ANd9GcT4H0uVJVHnlTMI5ik07_QrepcJuytHcDD5QN9LW_xX-9xSZMr6rHBxesjwl011KpjWpbdusIo", "rank" : "7", "sdoid" : "2", "search_count" : ">2000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:01:14 +0000", "title" : "Minnesota Wild", "url" : "www.nydailynews.com/entertainment/gossip/paul-simon-wife-edie-brickell-arrested-spat-connecticut-home-report-article-1.1771427", "woeid" : "23424977" },
{ "_id" : { "$oid" : "536568717d0ca84268af911d" }, "category" : null, "ctgl" : null, "image_url" : "t3.gstatic.com/images?q=tbn:ANd9GcRzy6rm1ghQsOIx1i5SjaYJO0_w69eXw0goG9CiBsIXKHxNVxT32W_9CZrBD6pojYLZvkqhhF8", "rank" : "8", "sdoid" : "2", "search_count" : ">2000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:01:14 +0000", "title" : "Abc3340", "url" : "www.usatoday.com/story/sports/nba/clippers/2014/04/29/donald-sterling-fine-penalty-racism-audio-commissioner-adam-silver-los-angeles-suspension/8460575/", "woeid" : "23424977" },
{ "_id" : { "$oid" : "536568717d0ca84268af911e" }, "category" : [ "/common/topic", null ], "ctgl" : [ "/common/topic" ], "image_url" : "t3.gstatic.com/images?q=tbn:ANd9GcR4DeABIcyLVxxA9-Dis0uucUTZnlCYq4b5d84VJN8mJjsaSwKqIj6N88-zuB317QJCtOu0TnR8", "rank" : "1", "sdoid" : "2", "search_count" : ">200", "the_date" : "20140429", "timestamp" : "2014-04-29 20:01:48 +0000", "title" : "selfie", "url" : "www.infonews.com/2014/04/28/sociedad-141606-murio-un-minuto-despues-de-postear-una-selfie-en-facebook-desde-el-auto.php", "woeid" : "23424747" },
{ "_id" : { "$oid" : "536568717d0ca84268af911f" }, "category" : [ "/music/recording", "/music/single" ], "ctgl" : [ "/music/recording", "/music/single", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcSr6GfLZ1RI0iXleGGNkSVt5QxN_QQ7xUGPGVOWEhR7g5crMzq9xkpVoOCQ4ojk8VB6-HYuInvK", "rank" : "2", "sdoid" : "2", "search_count" : ">200", "the_date" : "20140429", "timestamp" : "2014-04-29 20:01:48 +0000", "title" : "Martin Bossi", "url" : "www.infobae.com/2014/04/28/1560520-el-minuto-minuto-la-guerra-el-rating-la-tv-del-lunes", "woeid" : "23424747" },
{ "_id" : { "$oid" : "536568717d0ca84268af9120" }, "category" : [ "/people/person", "/film/actor" ], "ctgl" : [ "/people/person", "/film/actor", "/tv/tv_actor", "/user/narphorium/people/nndb_person", "/user/narphorium/people/topic", "/influence/influence_node", "/award/award_nominee", "/film/person_or_entity_appearing_in_film", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcRKwWEPYJZVDiE0YXJM_bAi7HDwBqX-QJpgV53RGMSsZtdhQGku3fVjXux6iiuzBceeetjv8GQ", "rank" : "1", "sdoid" : "2", "search_count" : ">1000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:02:22 +0000", "title" : "George Clooney", "url" : "www.nydailynews.com/entertainment/george-clooney-hitched-lawyer-amal-alamuddin-article-1.1772111", "woeid" : "23424748" },
{ "_id" : { "$oid" : "536568717d0ca84268af9121" }, "category" : null, "ctgl" : null, "image_url" : "t3.gstatic.com/images?q=tbn:ANd9GcT63S7nMVG-hrOo46PWE8948zOb0gijf-92sEd40dxwSLNJHklJWQjDpCddlJjPKy8SnR21rmg", "rank" : "2", "sdoid" : "2", "search_count" : ">1000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:02:22 +0000", "title" : "Who Won My Kitchen Rules 2014", "url" : "www.news.com.au/entertainment/tv/bree-and-jessica-beat-chloe-and-kelly-in-my-kitchen-rules-final/story-fn8yvfst-1226900148513", "woeid" : "23424748" },
{ "_id" : { "$oid" : "536568717d0ca84268af9122" }, "category" : [ "/people/person", "/common/topic" ], "ctgl" : [ "/people/person", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcQm3H1IkVVkb7yczacoj2cDWg7u3J3uhqRK-ybHv0VsKJK7eNpFJpJ45BUwp8P232tY1asLDB46", "rank" : "3", "sdoid" : "2", "search_count" : ">500", "the_date" : "20140429", "timestamp" : "2014-04-29 20:02:22 +0000", "title" : "Emma Stone", "url" : "www.hollywoodreporter.com/live-feed/video-emma-stone-takes-jimmy-699541", "woeid" : "23424748" },
{ "_id" : { "$oid" : "536568717d0ca84268af9123" }, "category" : [ "/tv/tv_program", "/common/topic" ], "ctgl" : [ "/tv/tv_program", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcTrPY2fysRTGY3IGj60c9l3zUkrwYD3DEkq_FbHe_AQULhwFV0gjjod3Dw_", "rank" : "1", "sdoid" : "2", "search_count" : ">200", "the_date" : "20140429", "timestamp" : "2014-04-29 20:02:55 +0000", "title" : "Heute", "url" : "www.kleinezeitung.at/steiermark/graz/3616529/sonderpruefung-steiermaerkischer-sparkasse.story", "woeid" : "23424750" },
{ "_id" : { "$oid" : "536568717d0ca84268af9124" }, "category" : [ "/business/business_location", "/dining/restaurant" ], "ctgl" : [ "/business/business_location", "/dining/restaurant", "/common/topic" ], "image_url" : "t3.gstatic.com/images?q=tbn:ANd9GcTYxaDib7XPkxqTr1KWhqxQV_e-d2A59eZmlk97Doc0ATHU1zaIYX-yCrY", "rank" : "2", "sdoid" : "2", "search_count" : ">100", "the_date" : "20140429", "timestamp" : "2014-04-29 20:02:55 +0000", "title" : "Steirereck", "url" : "www.laola1.at/de/sport-mix/tennis/atp/news/st-petersburg-wird-tel-aviv/page/83318-281-103---803.html", "woeid" : "23424750" },
{ "_id" : { "$oid" : "536568717d0ca84268af9125" }, "category" : [ "/film/film", "/base/greatfilms/ranked_item" ], "ctgl" : [ "/film/film", "/base/greatfilms/ranked_item", "/base/greatfilms/topic", "/award/award_winning_work", "/media_common/adaptation", "/media_common/adapted_work", "/award/ranked_item", "/base/disneyana/topic", "/base/movies1001/topic", "/award/award_nominated_work", "/media_common/netflix_title", "/amusement_parks/ride_theme", "/base/shanghaiinternationalfilmfestival/topic", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcTx1oMpeUq9aRBXwEcecBKz9181na0MBdRFZWt7osvnQJ5fdntdQJkKtBsH", "rank" : "3", "sdoid" : "2", "search_count" : ">100", "the_date" : "20140429", "timestamp" : "2014-04-29 20:02:55 +0000", "title" : "Burger King", "url" : "www.welt.de/kultur/medien/article127398540/Das-Testosteron-tropft-nur-so-aus-jeder-Szene.html", "woeid" : "23424750" },
{ "_id" : { "$oid" : "536568717d0ca84268af9126" }, "category" : [ "/common/topic", null ], "ctgl" : [ "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcRRe9_l87pg6ra0och7WNOTh3yIQ0NpI1vQf85y0vctn4kRfOEepPwxExMth0qrZNqh6fErcgA", "rank" : "1", "sdoid" : "2", "search_count" : ">200", "the_date" : "20140429", "timestamp" : "2014-04-29 20:03:31 +0000", "title" : "Gva", "url" : "www.lefigaro.fr/cinema/2014/04/29/03002-20140429ARTFIG00064-gerard-oury-et-sa-grande-vadrouille-celebres-par-google.php", "woeid" : "23424757" },
{ "_id" : { "$oid" : "536568717d0ca84268af9127" }, "category" : [ "/music/recording", "/music/single" ], "ctgl" : [ "/music/recording", "/music/single", "/common/topic" ], "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcTLczBWgdNJnfB-pbCIvMhe1dfXX9s5quANuViX1-EcBV-Tb_cCYHcD3geaafAH9flH-0P3k-E", "rank" : "1", "sdoid" : "2", "search_count" : ">2000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:06:18 +0000", "title" : "Novinky", "url" : "www.novinky.cz/zena/zdravi/334770-obavy-a-uzkosti-trapi-az-polovinu-cechu.html", "woeid" : "23424810" },
{ "_id" : { "$oid" : "536568717d0ca84268af9128" }, "category" : [ "/location/citytown", "/protected_sites/listed_site" ], "ctgl" : [ "/location/citytown", "/protected_sites/listed_site", "/location/administrative_division", "/user/brendan/default_domain/top_architectural_city", "/location/dated_location", "/film/film_location", "/user/robert/default_domain/my_favorite_things", "/travel/travel_destination", "/people/place_of_interment", "/base/popstra/topic", "/base/popstra/sww_base", "/base/popstra/location", "/base/arthist/helynevek", "/book/book_subject", "/base/ontologies/ontology_instance", "/base/tagit/place", "/base/biblioness/bibs_location", "/base/biblioness/bibs_topic", "/base/aareas/schema/cz/region", "/base/aareas/schema/administrative_area", "/base/aareas/schema/cz/oblast", "/base/aareas/topic", "/location/capital_of_administrative_division", "/symbols/name_source", "/periodicals/newspaper_circulation_area", "/government/governmental_jurisdiction", "/common/topic", "/location/location", "/location/statistical_region", "/base/type_ontology/inanimate", "/base/type_ontology/abstract" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcQEDtWxdnZtxjRRhcuNPUd6ChM9IKbe37UZTIUhqST87vyMkS84qPXNsa4CTbhyTpdw75ad0HY", "rank" : "2", "sdoid" : "2", "search_count" : ">200", "the_date" : "20140429", "timestamp" : "2014-04-29 20:06:18 +0000", "title" : "Lev Praha", "url" : "www.denik.cz/ekonomika/mbank-stouply-v-1-ctvrtleti-vynosy-o-76-procent-na-167-milionu-korun-20140428.html", "woeid" : "23424810" },
{ "_id" : { "$oid" : "536568717d0ca84268af9129" }, "category" : [ "/organization/organization", "/business/employer" ], "ctgl" : [ "/organization/organization", "/business/employer", "/user/bhludzin/default_domain/bank", "/projects/project_focus", "/organization/organization_member", "/base/estonia/topic", "/base/bangladesh/topic", "/base/unitednations/united_nations_agency", "/base/unitednations/topic", "/business/business_operation", "/organization/membership_organization", "/book/author", "/base/elbogen/topic", "/base/elbogen/meeting_organizer", "/base/schemastaging/context_name", "/base/schemastaging/organization_extra", "/common/topic", "/dataworld/data_provider" ], "image_url" : "t0.gstatic.com/images?q=tbn:ANd9GcQK0gJgEetQOXHxm17bWusn2pdGDDaVdxan_yOajqE2E8Kq2ltmzahzpHm7dNdZqEmIVKOpBHs", "rank" : "3", "sdoid" : "2", "search_count" : ">100", "the_date" : "20140429", "timestamp" : "2014-04-29 20:06:18 +0000", "title" : "mBank", "url" : "www.ceskatelevize.cz/ct24/domaci/271119-premierske-pokani-gross-se-v-ct-verejne-omluvil-vsem-ktere-zklamal/", "woeid" : "23424810" },
{ "_id" : { "$oid" : "536568717d0ca84268af912a" }, "category" : [ "/computer/software_developer", "/user/joehughes/default_domain/transit_application_creator" ], "ctgl" : [ "/computer/software_developer", "/user/joehughes/default_domain/transit_application_creator", "/business/employer", "/user/rcheramy/default_domain/manufacturer", "/venture_capital/venture_funded_company", "/internet/website_owner", "/venture_capital/venture_investor", "/user/robert/default_domain/logos", "/award/award_presenting_organization", "/base/database/topic", "/base/database/database_financial_supporter", "/base/database/database_host", "/book/book_subject", "/organization/organization_founder", "/organization/organization_member", "/award/ranked_item", "/internet/social_network_user", "/user/vtalwar/default_domain/logoed_topic", "/base/onewayshopping/topic", "/computer/operating_system_developer", "/base/informationtechnology/topic", "/business/sponsor", "/user/mr_kav/default_domain/program", "/base/argumentmaps/thing_of_disputed_value", "/base/argumentmaps/topic", "/base/adidtest/topic", "/business/business_operation", "/business/issuer", "/base/todolists/topic", "/computer/programming_language_developer", "/user/uoa_it/uoa_it/uoa_vendor", "/user/uoa_it/uoa_it/topic", "/organization/organization", "/base/internettechnology/topic", "/m/0cgxpqv", "/m/0cgyc3f", "/base/ovguide/topic", "/business/consumer_company", "/conferences/conference_sponsor", "/user/whurrraywebworld/default_domain/whurray", "/base/ecology/topic", "/projects/project_participant", "/law/patent_assignee", "/base/technologyofdoing/proposal_agent", "/computer/computer_manufacturer_brand", "/user/robert/mobile_phones/mobile_phone_brand", "/user/robert/mobile_phones/product_brand", "/law/litigant", "/dataworld/data_provider", "/base/schemastaging/organization_extra", "/user/alust/default_domain/processed_with_review_queue", "/film/film_subject", "/conferences/conference_subject", "/freebase/list", "/award/award_winner", "/architecture/architectural_structure_owner", "/m/04mny2g", "/user/micahsaul/advertising/advertiser", "/award/award_nominee", "/location/location", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcQVYqoara5ANDtqh5L0NCuoy75PbA6JXegR-0joO0r_75Wy9Hj4xHLNIzBO3N2Zzqdw4cN74OLc", "rank" : "1", "sdoid" : "2", "search_count" : ">100", "the_date" : "20140429", "timestamp" : "2014-04-29 20:06:53 +0000", "title" : "Translate Google", "url" : "www.nlnewsnow.com/Community-/2014-04-28/article-3702207/Social-Notes/1", "woeid" : "23424796" },
{ "_id" : { "$oid" : "536568717d0ca84268af912b" }, "category" : null, "ctgl" : null, "image_url" : "t3.gstatic.com/images?q=tbn:ANd9GcQ47ZpygEF4xvOX60QeLhatnh27pAK_I_ob2kvUiphMctlxvo1ZewqDdJM", "rank" : "1", "sdoid" : "2", "search_count" : ">200", "the_date" : "20140429", "timestamp" : "2014-04-29 20:08:01 +0000", "title" : "Amal Alamuddin", "url" : "www.bloomberg.com/news/2014-04-29/nokia-names-suri-ceo-to-revive-technology-pioneer-without-phones.html", "woeid" : "23424812" },
{ "_id" : { "$oid" : "536568717d0ca84268af912c" }, "category" : [ "/computer/computer_manufacturer_brand", "/cvg/cvg_publisher" ], "ctgl" : [ "/computer/computer_manufacturer_brand", "/cvg/cvg_publisher", "/internet/top_level_domain_sponsor", "/computer/software_developer", "/business/employer", "/venture_capital/venture_funded_company", "/venture_capital/venture_investor", "/user/robert/mobile_phones/product_brand", "/user/alexander/default_domain/headphone_manufacturer", "/internet/website_owner", "/user/robert/mobile_phones/topic", "/base/gadgets/topic", "/base/gadgets/brand", "/organization/organization_member", "/user/robert/mobile_phones/mobile_phone_brand", "/business/sponsor", "/computer/operating_system_developer", "/base/vancouver2010/topic", "/base/ontologies/ontology_instance", "/business/business_operation", "/award/ranked_item", "/cvg/cvg_developer", "/organization/organization", "/base/internettechnology/topic", "/business/issuer", "/base/tagit/concept", "/business/consumer_company", "/base/ovguide/topic", "/business/customer", "/conferences/conference_sponsor", "/organization/organization_partnership", "/projects/project_participant", "/base/schemastaging/organization_extra", "/award/award_nominee", "/award/award_winner", "/film/production_company", "/user/micahsaul/advertising/advertiser", "/m/04mny2g", "/common/topic" ], "image_url" : "t0.gstatic.com/images?q=tbn:ANd9GcS8zJfa0RRiFNNIXX6S-QNphdKYGj3p3diMK3tPPl5CJ3Gd9JrJqLGGeZNv", "rank" : "2", "sdoid" : "2", "search_count" : ">100", "the_date" : "20140429", "timestamp" : "2014-04-29 20:08:01 +0000", "title" : "Nokia", "url" : "www.advocate.com/commentary/2014/04/28/op-ed-why-i-take-prep", "woeid" : "23424812" },
{ "_id" : { "$oid" : "536568717d0ca84268af912d" }, "category" : [ "/common/document", null ], "ctgl" : [ "/common/document" ], "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcQwpdbgQTgSIFDe3F8kPRviWcsGxmKcieOydh8cSLqRcLiawgOxNREfMpM", "rank" : "1", "sdoid" : "2", "search_count" : ">10000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:08:34 +0000", "title" : "Alix Bachelor", "url" : "www.public.fr/Toutes-les-interviews/Exclu-Public-Alix-Bachelor-Paul-m-a-tout-de-suite-integree-a-son-entourage-a-Singapour-526781", "woeid" : "23424819" },
{ "_id" : { "$oid" : "536568717d0ca84268af912e" }, "category" : [ "/base/dinosaur/dinosaur_diet", "/base/birdinfo/type_of_diet" ], "ctgl" : [ "/base/dinosaur/dinosaur_diet", "/base/birdinfo/type_of_diet", "/base/birdinfo/topic", "/user/pak21/bbcnathist/adaptation", "/book/book_subject", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcRrXiH_7RA5mREjBVPTV2xiVpvZjFOXjR51ZbPTlcI44pGICo1vZXIveTo", "rank" : "2", "sdoid" : "2", "search_count" : ">2000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:08:34 +0000", "title" : "Aymeric Caron", "url" : "www.lefigaro.fr/cinema/2014/04/29/03002-20140429ARTFIG00064-gerard-oury-et-sa-grande-vadrouille-celebres-par-google.php", "woeid" : "23424819" },
{ "_id" : { "$oid" : "536568717d0ca84268af912f" }, "category" : [ "/people/person", "/people/deceased_person" ], "ctgl" : [ "/people/person", "/people/deceased_person", "/government/politician", "/book/author", "/user/alust/default_domain/processed_with_review_queue", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcRjzdWFsUYk6Rou84-ZUqEfHtkd2yZYNebJTyKujaJ_4rO2wz4JgqKC9adw", "rank" : "3", "sdoid" : "2", "search_count" : ">1000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:08:34 +0000", "title" : "Jean Imbert", "url" : "www.rtl.fr/actualites/television/article/top-chef-jean-imbert-perd-le-choc-des-champions-face-a-pierre-auge-7771547302", "woeid" : "23424819" },
{ "_id" : { "$oid" : "536568717d0ca84268af9130" }, "category" : [ "/people/person", "/olympics/olympic_athlete" ], "ctgl" : [ "/people/person", "/olympics/olympic_athlete", "/sports/pro_athlete", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcSs75nxxXHxmCos1PuOZ3Xtq585SppBxy7VhJHstaNryIJBYlpUkAVlQa8", "rank" : "4", "sdoid" : "2", "search_count" : ">1000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:08:34 +0000", "title" : "Nathalie Pechalat", "url" : "www.lefigaro.fr/culture/2014/04/28/03004-20140428ARTFIG00303-micheline-dax-l-hommage-unanime-de-ses-nombreux-admirateurs.php", "woeid" : "23424819" },
{ "_id" : { "$oid" : "536568717d0ca84268af9131" }, "category" : [ "/people/person", "/visual_art/visual_artist" ], "ctgl" : [ "/people/person", "/visual_art/visual_artist", "/people/deceased_person", "/influence/influence_node", "/visual_art/art_subject", "/symbols/name_source", "/user/narphorium/people/nndb_person", "/exhibitions/exhibition_subject", "/user/skud/names/topic", "/user/narphorium/people/topic", "/base/printmaking/topic", "/base/atheism/topic", "/book/book_subject", "/base/smarthistory/topic", "/base/smarthistory/visual_artist", "/book/author", "/film/film_subject", "/book/illustrator", "/base/ontologies/ontology_instance", "/base/kwebbase/kwtopic", "/base/patronage/client", "/base/tagit/concept", "/fictional_universe/person_in_fiction", "/base/activism/topic", "/base/activism/activist", "/film/person_or_entity_appearing_in_film", "/medicine/notable_person_with_medical_condition", "/base/armoryshow1913/exhibited_artist", "/base/armoryshow1913/topic", "/base/schemastaging/context_name", "/base/schemastaging/topic", "/tv/tv_subject", "/base/allthingsnewyork/topic", "/award/award_winner", "/film/film_production_designer", "/film/film_costumer_designer", "/film/actor", "/film/film_story_contributor", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcTB5By4cpOoOtvdKTBIu8sKti77V5mbCIYH9d43y8HYgPQC2KwMizuGcprl", "rank" : "5", "sdoid" : "2", "search_count" : ">1000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:08:34 +0000", "title" : "Picasso", "url" : "www.lefigaro.fr/cinema/2014/04/29/03002-20140429ARTFIG00207--star-wars-vii-oscar-isaac-au-casting-harrison-ford-au-coeur-de-l-intrigue.php", "woeid" : "23424819" },
{ "_id" : { "$oid" : "536568717d0ca84268af9132" }, "category" : [ "/music/artist", "/people/person" ], "ctgl" : [ "/music/artist", "/people/person", "/music/group_member", "/film/actor", "/film/writer", "/broadcast/artist", "/celebrities/celebrity", "/user/narphorium/people/nndb_person", "/user/narphorium/people/topic", "/award/award_nominee", "/people/measured_person", "/base/popstra/sww_base", "/base/popstra/celebrity", "/base/popstra/topic", "/base/myspace/myspace_user", "/internet/social_network_user", "/tv/tv_actor", "/film/person_or_entity_appearing_in_film", "/music/producer", "/influence/influence_node", "/tv/tv_program_guest", "/base/schemastaging/person_extra", "/film/film_story_contributor", "/base/schemastaging/context_name", "/organization/organization_founder", "/music/lyricist", "/music/composer", "/music/featured_artist", "/award/award_winner", "/common/topic" ], "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcSp9NbRCdmtZ9ZhHxP7REb5n_6kkIvwclVyaxgI7no5fJgFadJULuliYlU", "rank" : "6", "sdoid" : "2", "search_count" : ">500", "the_date" : "20140429", "timestamp" : "2014-04-29 20:08:34 +0000", "title" : "Noma", "url" : "www.sciencesetavenir.fr/sante/20140429.OBS5544/video-10-ans-de-colonisation-par-le-moustique-tigre.html", "woeid" : "23424819" },
{ "_id" : { "$oid" : "536568717d0ca84268af9133" }, "category" : [ "/location/country", "/organization/organization_member" ], "ctgl" : [ "/location/country", "/organization/organization_member", "/fictional_universe/fictional_setting", "/location/dated_location", "/military/military_combatant", "/symbols/name_source", "/food/beer_country_region", "/olympics/olympic_participating_country", "/government/governmental_jurisdiction", "/user/robert/military/military_power", "/symbols/flag_referent", "/user/skud/flags/topic", "/user/skud/names/topic", "/user/robert/military/topic", "/base/petbreeds/topic", "/book/book_subject", "/user/tsegaran/random/taxonomy_subject", "/biology/breed_origin", "/symbols/coat_of_arms_bearer", "/base/worldwartwo/topic", "/base/languagesfordomainnames/topic", "/sports/sports_team_location", "/organization/organization_scope", "/base/jewlib/topic", "/base/jewlib/parent_institution", "/base/vancouver2010/topic", "/base/ontologies/ontology_instance", "/base/masterthesis/topic", "/sports/sport_country", "/film/film_festival_focus", "/media_common/netflix_genre", "/periodicals/newspaper_circulation_area", "/base/biblioness/bibs_topic", "/base/biblioness/bibs_location", "/base/aareas/schema/earth/sovereign_state", "/base/aareas/schema/administrative_area", "/base/uncommon/topic", "/base/locations/topic", "/base/locations/countries", "/base/historiaswidnika/topic", "/film/film_location", "/organization/organization_founder", "/common/topic", "/location/location", "/location/statistical_region", "/base/type_ontology/inanimate", "/base/type_ontology/abstract" ], "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcQSx_VWaF-0PFnaoZWtA762dfjj5ceJvgET2aHFDL7WDT4AOPEE9pv4t_Y", "rank" : "7", "sdoid" : "2", "search_count" : ">500", "the_date" : "20140429", "timestamp" : "2014-04-29 20:08:34 +0000", "title" : "pole", "url" : "www.voici.fr/news-people/actu-people/albert-de-monaco-la-mere-de-son-fils-l-accuse-de-l-avoir-delaisse-a-cause-de-charlene-529625", "woeid" : "23424819" },
{ "_id" : { "$oid" : "536568717d0ca84268af9134" }, "category" : [ "/government/government_agency", "/organization/organization" ], "ctgl" : [ "/government/government_agency", "/organization/organization", "/business/employer", "/business/business_operation", "/common/topic" ], "image_url" : "t3.gstatic.com/images?q=tbn:ANd9GcRQYfkYhkMjn94t51NxnG84b3s80kHw9VV-0xsgKBRRns30KjPKz-tOL-cw", "rank" : "8", "sdoid" : "2", "search_count" : ">500", "the_date" : "20140429", "timestamp" : "2014-04-29 20:08:34 +0000", "title" : "Pole Emploi", "url" : "www.europe1.fr/France/Jamel-Leulmi-est-un-tres-beau-manipulateur-2105801/", "woeid" : "23424819" },
{ "_id" : { "$oid" : "536568717d0ca84268af9135" }, "category" : [ "/tv/tv_program", "/common/topic" ], "ctgl" : [ "/tv/tv_program", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcRPdJkADrBuvccGVbfUC_7dvOVbv78dhfa6HEDb3mJ1iWHvVQbP9UifBAlu", "rank" : "1", "sdoid" : "2", "search_count" : ">2000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:09:07 +0000", "title" : "Circus HalliGalli", "url" : "www.ampya.com/news/Aktuell/Lykke-Li-heute-Abend-zu-Gast-bei-Circus-HalliGalli-SN108531/", "woeid" : "23424829" },
{ "_id" : { "$oid" : "536568717d0ca84268af9136" }, "category" : [ "/music/artist", "/music/musical_group" ], "ctgl" : [ "/music/artist", "/music/musical_group", "/music/producer", "/award/award_nominee", "/award/award_winner", "/common/topic" ], "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcS4xIuC0gaFCDM6hszzno-S1KjNWYUSxkLw-eex-oYsdGwBO3tZyY1B5fZrGB_EglXf_rgHJzU", "rank" : "1", "sdoid" : "2", "search_count" : ">500", "the_date" : "20140429", "timestamp" : "2014-04-29 20:10:13 +0000", "title" : "2ne1", "url" : "www.chinatimes.com/newspapers/20140426000827-260112", "woeid" : "24865698" },
{ "_id" : { "$oid" : "536568717d0ca84268af9137" }, "category" : [ "/business/employer", "/organization/organization" ], "ctgl" : [ "/business/employer", "/organization/organization", "/business/business_operation", "/base/schemastaging/organization_extra", "/common/topic" ], "image_url" : "t0.gstatic.com/images?q=tbn:ANd9GcTw1qXlVy3VwFAFpT_a7xDUvAmYgRT6hBi4KK6l4PAxJI1Um5WljyLVsKlu9RXJVjyBBBXAEBBh", "rank" : "1", "sdoid" : "2", "search_count" : ">100", "the_date" : "20140429", "timestamp" : "2014-04-29 20:10:49 +0000", "title" : "OTP", "url" : "www.origo.hu/itthon/20140427-elindult-az-elet-menete.html", "woeid" : "23424844" },
{ "_id" : { "$oid" : "536568717d0ca84268af9138" }, "category" : [ "/people/profession", "/base/ontologies/ontology_instance" ], "ctgl" : [ "/people/profession", "/base/ontologies/ontology_instance", "/base/tagit/concept", "/base/skosbase/vocabulary_equivalent_topic", "/base/skosbase/topic", "/user/alust/default_domain/processed_with_review_queue", "/common/topic" ], "image_url" : "t3.gstatic.com/images?q=tbn:ANd9GcSm1rJJlcV8b8RbQiAOf5p-R3M6j_xZVEN5Cqb8VcSR8kjnIMe3L5v5UbVIesOC8mQVxDsAsRg", "rank" : "1", "sdoid" : "2", "search_count" : ">5000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:11:23 +0000", "title" : "jac", "url" : "www.mid-day.com/articles/senior-ap-intermediate-12th-result-2014-2nd-year-ap-inter-result-2014-is-expected-to-be-declared-soon/15261083", "woeid" : "23424848" },
{ "_id" : { "$oid" : "536568717d0ca84268af9139" }, "category" : [ "/music/album", "/common/topic" ], "ctgl" : [ "/music/album", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcQRXHgnaUJpq_23KXbnNAnmkY4oq--gFpTc7cV5YgWoWHVI1gJrEWlCjYxgfcqDIzTesPo55sJl", "rank" : "2", "sdoid" : "2", "search_count" : ">5000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:11:23 +0000", "title" : "Alla Rakha", "url" : "www.ndtv.com/elections/article/election-2014/bjp-s-sharpest-attack-ever-on-robert-vadra-514815", "woeid" : "23424848" },
{ "_id" : { "$oid" : "536568717d0ca84268af913a" }, "category" : null, "ctgl" : null, "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcRZlMtIUw8hGV0_5ybwgR6g6Itxh06hy11TPA76Gpzp8GbhQ4X0Lzy220FCVQ2siB8IBaeZDkY", "rank" : "1", "sdoid" : "2", "search_count" : ">2000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:11:56 +0000", "title" : "Prediksi Munchen Vs Madrid", "url" : "www.solopos.com/2014/04/29/prediksi-bayern-munchen-vs-real-madrid-rekor-kandang-jadi-andalan-505137", "woeid" : "23424846" },
{ "_id" : { "$oid" : "536568717d0ca84268af913b" }, "category" : [ "/common/topic", "/base/semanticnames/topic" ], "ctgl" : [ "/common/topic", "/base/semanticnames/topic", "/base/semanticnames/personal_name_type", "/base/references/greek_loanword", "/base/references/topic" ], "image_url" : "t0.gstatic.com/images?q=tbn:ANd9GcT29HBGvQfhdHbbdh-puDOV-_JyCSThVwTznzUc5vK8BhcIiRTeviAGv3cjeq0yvQqdv_-kfGE", "rank" : "2", "sdoid" : "2", "search_count" : ">2000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:11:56 +0000", "title" : "Aliando", "url" : "www.pehtem.com/13649/aliando-syarief-idola-baru-remaja-putri", "woeid" : "23424846" },
{ "_id" : { "$oid" : "536568717d0ca84268af913c" }, "category" : [ "/time/day_of_year", "/common/topic" ], "ctgl" : [ "/time/day_of_year", "/common/topic" ], "image_url" : "t0.gstatic.com/images?q=tbn:ANd9GcTjte7NGOwyN_33oRkYYY4P-X70k0tbZjCwlHfuzo7WUb2U15dpFrpgUiK0rnlsNt9g14cT6sAY", "rank" : "3", "sdoid" : "2", "search_count" : ">500", "the_date" : "20140429", "timestamp" : "2014-04-29 20:11:56 +0000", "title" : "Ganjar Pranowo", "url" : "www.tempo.co/read/news/2014/04/29/111574192/Ini-Perasaan-Sarah-Carter-Main-Film-di-Indonesia", "woeid" : "23424846" },
{ "_id" : { "$oid" : "536568717d0ca84268af913d" }, "category" : [ "/people/person", "/film/actor" ], "ctgl" : [ "/people/person", "/film/actor", "/common/topic" ], "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcQ5HOfyPwNxo4iC0d8kTs9py4uC7cns_jkBWJveevNyX52O--A6NQ3mC_dFaDVTCbPx_VT4Tgcz", "rank" : "4", "sdoid" : "2", "search_count" : ">500", "the_date" : "20140429", "timestamp" : "2014-04-29 20:11:56 +0000", "title" : "Sarah Carter", "url" : "www.tempo.co/read/news/2014/04/29/058574125/Banyak-Pendaki-Tanyakan-Kondisi-Gunung-Slamet", "woeid" : "23424846" },
{ "_id" : { "$oid" : "536568717d0ca84268af913e" }, "category" : [ "/location/location", "/geography/mountain" ], "ctgl" : [ "/location/location", "/geography/mountain", "/base/indonesia/topic", "/geography/geographical_feature", "/common/topic" ], "image_url" : "t2.gstatic.com/images?q=tbn:ANd9GcSKNqGBaNKVQ-Qj4edExi5jQB3d_zYQ-gmI19Ow8cfLTRAn183ueymCaEQnKOkpXi_J1wOcRYl1", "rank" : "5", "sdoid" : "2", "search_count" : ">500", "the_date" : "20140429", "timestamp" : "2014-04-29 20:11:56 +0000", "title" : "Gunung Slamet", "url" : "www.tribunnews.com/superball/2014/04/28/hasil-lengkap-dan-klasemen-liga-inggris-sampai-senin-284", "woeid" : "23424846" },
{ "_id" : { "$oid" : "536568717d0ca84268af9143" }, "category" : null, "ctgl" : null, "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcQ3fu4Zy7mLY_Q9u1e0Bcgk7NhoQr5-ZjoOjlnh8BYddvRV7FrAJG74tBgJ0NN2AGFrJCMkWMc", "rank" : "1", "sdoid" : "2", "search_count" : ">1000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:13:04 +0000", "title" : "incentivi auto 2014", "url" : "www.ilpost.it/2014/04/29/incentivi-auto-2014/", "woeid" : "23424853" },
{ "_id" : { "$oid" : "536568717d0ca84268af9144" }, "category" : null, "ctgl" : null, "image_url" : "t0.gstatic.com/images?q=tbn:ANd9GcRyAU9bxOib9XwKhX_rDzWKMmN8QJarMTmSKafuqHNn5VfC3UMz4pjip3JfRfxgXekkOt76RGY", "rank" : "2", "sdoid" : "2", "search_count" : ">500", "the_date" : "20140429", "timestamp" : "2014-04-29 20:13:04 +0000", "title" : "Anticipazioni Amici", "url" : "www.gazzetta.it/Calcio/Serie-A/Juventus/28-04-2014/sassuolo-juventus-conte-garcia-nervoso-alimenta-solo-sospetti-80541978973.shtml", "woeid" : "23424853" },
{ "_id" : { "$oid" : "536568717d0ca84268af9145" }, "category" : [ "/location/country", "/military/military_combatant" ], "ctgl" : [ "/location/country", "/military/military_combatant", "/government/governmental_jurisdiction", "/location/dated_location", "/film/film_subject", "/organization/organization_member", "/book/book_subject", "/olympics/olympic_participating_country", "/food/beer_country_region", "/organization/organization_scope", "/base/charities/geographic_scope", "/user/robert/military/military_power", "/royalty/kingdom", "/symbols/flag_referent", "/user/skud/flags/topic", "/user/robert/military/topic", "/base/charities/topic", "/base/petbreeds/topic", "/film/film_location", "/base/thoroughbredracing/thoroughbred_racehorse_origin", "/user/robert/mobile_phones/mobile_phone_region", "/user/tsegaran/random/taxonomy_subject", "/base/survivor/topic", "/base/marsupials/topic", "/biology/breed_origin", "/base/mystery/cryptid_observation_location", "/base/mystery/cryptid_area_of_occurrence", "/base/mystery/topic", "/symbols/coat_of_arms_bearer", "/base/vietnamwar/topic", "/base/worldwartwo/topic", "/base/anzacs/topic", "/base/languagesfordomainnames/topic", "/sports/sports_team_location", "/base/popstra/location", "/base/popstra/sww_base", "/base/popstra/topic", "/fictional_universe/fictional_setting", "/base/seafood/fishery_location", "/base/seafood/topic", "/base/vancouver2010/topic", "/cvg/computer_game_region", "/sports/sport_country", "/base/masterthesis/topic", "/base/coloniesandempire/existing_british_colonies_dominions_and_protectorates", "/base/coloniesandempire/topic", "/base/tagit/concept", "/law/court_jurisdiction_area", "/user/skud/legal/topic", "/base/musicvideos/topic", "/music/music_video_subject", "/base/sharing/topic", "/base/sharing/sharing_location", "/base/caveart/region", "/base/folklore/mythical_creature_location", "/base/biblioness/bibs_topic", "/base/biblioness/bibs_location", "/base/aareas/schema/earth/sovereign_state", "/base/aareas/schema/administrative_area", "/periodicals/newspaper_circulation_area", "/base/uncommon/topic", "/tv/tv_location", "/organization/organization_founder", "/base/skosbase/vocabulary_equivalent_topic", "/base/skosbase/topic", "/government/government", "/travel/travel_destination", "/business/business_location", "/business/employer", "/common/topic", "/location/location", "/location/statistical_region", "/base/type_ontology/inanimate", "/base/type_ontology/abstract" ], "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcSx0t45DTD_mZHSCvbsOrmMCGE6Qs4hPeLLOd_-ubk1N5x6RDDCBMr9B3oTaktL1DsumDWUhXUD", "rank" : "3", "sdoid" : "2", "search_count" : ">500", "the_date" : "20140429", "timestamp" : "2014-04-29 20:13:04 +0000", "title" : "Report", "url" : "www.gazzetta.it/Formula-1/28-04-2014/senna-imola-ferrari-presente-alonso-raikkonen-80539151612.shtml", "woeid" : "23424853" },
{ "_id" : { "$oid" : "536568717d0ca84268af9146" }, "category" : [ "/user/robert/mobile_phones/mobile_phone_operating_system", "/user/robert/mobile_phones/topic" ], "ctgl" : [ "/user/robert/mobile_phones/mobile_phone_operating_system", "/user/robert/mobile_phones/topic", "/computer/operating_system", "/cvg/cvg_platform", "/base/mobilecomputers/topic", "/base/mobilecomputers/mobile_operating_system", "/computer/software", "/common/topic" ], "image_url" : "t3.gstatic.com/images?q=tbn:ANd9GcQYlrJRb5efHJKANTRmXf-kp7yzolMlrR92CLOMIMFo5k0ON-BO8BJeH84ovY-bu9F0hwKDSBZf", "rank" : "1", "sdoid" : "2", "search_count" : ">5000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:13:42 +0000", "title" : "Ie", "url" : "www.asahi.com/articles/ASG4Y3J2BG4YOHGB003.html", "woeid" : "23424856" },
{ "_id" : { "$oid" : "536568717d0ca84268af9147" }, "category" : [ "/business/employer", "/organization/organization" ], "ctgl" : [ "/business/employer", "/organization/organization", "/business/business_operation", "/common/topic" ], "image_url" : "t1.gstatic.com/images?q=tbn:ANd9GcSPy39AED07_j2wQWq8um2liBQUgPL751TVrooeIaIY6lXyhL-mOPdrK-mLwfZ1uSKip_fo-w", "rank" : "2", "sdoid" : "2", "search_count" : ">5000", "the_date" : "20140429", "timestamp" : "2014-04-29 20:13:42 +0000", "title" : "JTB", "url" : "www.asahi.com/articles/ASG4X641QG4XUCVL023.html", "woeid" : "23424856" }
];

var items={
 "name": "social media",
 "children": 
 [
  {
   "name": "google",
   "children": 
   [
    {"name": "Music", "children": 
      [
        {"name": "Trend1", "size": 3938}
      ]

    },
    {"name": "Sports", "children": 
      [
        {"name": "Trend1", "size": 3938}
      ]

    }

   ]
  },
  {
   "name": "instagram",
   "children": 
   [
    {"name": "Music", "children": 
      [
        {"name": "Trend1", "size": 3938}
      ]

    }
   ]
  } 
 ]
};


$(document).ready(function () {

	createGoogleObject();
  //your code here
});

var catGoogleArr=[];


function createGoogleObject(){
		console.log("inside  google object");

		
		$.each(googleArr, function(index, value ) 
		{
		var obj={};
		

		$.each(value.ctgl, function(indexCat, valueCat ) {

			if(valueCat!=null){
				console.log(value.ctgl[1]);




			}

  			
		});

		
		
		});
		console.log("Pringting Goog le inner Array");
		
    	


 
}